name: action-example
on:
  push:
    branches:
      - main
jobs:
  action-example:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: "15.8.0"

      - name: npm ci
        run: npm ci
        shell: bash

      - name: run script
        run: node hello.js
        shell: bash
