name: hello-world-example
on:
  push:
    branches:
      - "dev/**"
      - "!main"
  pull_request:
    branches:
      - "staging"

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello world!"
      - name: Do stuff
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
      - name: Triggered by
        run: echo "Triggered by ${{ github.event_name }}"
