name: job-matrix
on:
  push:
    branches: ["*"]

jobs:
  job-matrix-example:
    strategy:
      matrix:
        # 2*2 이므로 총 4가지 경우의 job이 발생함
        os: [ubuntu-latest, ubuntu-18.04]
        node-version: [12, 14]

    runs-on: ${{matrix.os}}

    steps:
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: check node version
        run: node --version
        shell: bash
