name: parallel-jobs-example
on:
  push:
    branches: ["*"]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: echo wassup
        run: echo "wassup"

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: echo hi
        run: echo "hi"
        shell: bash
